### ISSUE TITLE
catkin_make problem with dc_smach

### ISSUE THREAD

**Issue by julianrotheric** [atorment/deep-animal#5]
After a git pull, going up a directory, and running catkin_make I get the following error. This is a problem with dc_smach.

CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "test_action_client_server" with any of the following names:

    test_action_client_serverConfig.cmake
    test_action_client_server-config.cmake

  Add the installation prefix of "test_action_client_server" to
  CMAKE_PREFIX_PATH or set "test_action_client_server_DIR" to a directory
  containing one of the above files.  If "test_action_client_server" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  dc_smach/CMakeLists.txt:5 (find_package)

-- Could not find the required component 'test_action_client_server'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "test_action_client_server" with any of the following names:

    test_action_client_serverConfig.cmake
    test_action_client_server-config.cmake

  Add the installation prefix of "test_action_client_server" to
  CMAKE_PREFIX_PATH or set "test_action_client_server_DIR" to a directory
  containing one of the above files.  If "test_action_client_server" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  dc_smach/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/precision/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/precision/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by atorment** [comment]
@julianrotheric you might have the test_action_client_server folder included in your /src. That folder is no longer needed. Try removing the test_action_client_server folder from /src and do another catkin_make. All packages not included in the repository but are required to build are included in the .gitignore, all other packages should be removed.

**Comment by gjt-cmyk** [comment]
test_action_client_server was an old package in dc_smach that has since been removed. You can try first cloning the repo and make:

```
cd ~/catkin_ws/
git clone origin https://github.com/atorment/deep-animal.git src
catkin_make
```
or you can try to download the dc_smach package directly into your local repo (download repo zip and copy and paste the dc_smach folder in).

I would also look at the dc_smach/package.xml file, local and remote, and see if they are the same. Specifically, remove the line in dc_smach/package.xml:

`<depend>test_action_client_server</depend>`

(this was removed in https://github.com/atorment/deep-animal/commit/e4d2755752f9204c20add7c75ecb9d391def4991)

**Comment by julianrotheric** [comment]
I removed <depend>test_action_client_server</depend> from dc_smach/package.xml and I had to remove test_action_client_server from CMakeLists.txt and it worked!
